let tokenCache={token:null,expiresAt:0};
const WCL_TOKEN='https://www.warcraftlogs.com/oauth/token';
const WCL_GRAPHQL='https://www.warcraftlogs.com/api/v2/client';
function cors(origin='*'){return {'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Methods':'GET,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Authorization','Content-Type':'application/json;charset=utf-8'}}
async function token(env){if(tokenCache.token&&Date.now()<tokenCache.expiresAt-60000)return tokenCache.token;const basic=btoa(`${env.WCL_CLIENT_ID}:${env.WCL_CLIENT_SECRET}`);const r=await fetch(WCL_TOKEN,{method:'POST',headers:{Authorization:`Basic ${basic}`,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});if(!r.ok)throw new Error(`OAuth ${r.status}: ${await r.text()}`);const j=await r.json();tokenCache={token:j.access_token,expiresAt:Date.now()+(j.expires_in||3600)*1000};return j.access_token}
async function gql(env,query,variables){const t=await token(env);const r=await fetch(WCL_GRAPHQL,{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({query,variables})});const j=await r.json();if(!r.ok||j.errors)throw new Error(JSON.stringify(j.errors||j));return j.data}
const META=`query($code:String!,$fightIDs:[Int]){reportData{report(code:$code){title startTime masterData{actors{id name type subType}} fights(fightIDs:$fightIDs){id name startTime endTime encounterID difficulty kill friendlyPlayers}}}}`;
const EVENTS=`query($code:String!,$fightIDs:[Int],$startTime:Float){reportData{report(code:$code){events(fightIDs:$fightIDs,startTime:$startTime,limit:10000){data nextPageTimestamp}}}}`;
function readResource(res){if(!res||typeof res!=='object')return null;const x=Number(res.x),y=Number(res.y);return Number.isFinite(x)&&Number.isFinite(y)?{x,y}:null}
function normalize(meta,rawEvents,reportCode,fightId){const report=meta.reportData?.report;if(!report)throw new Error('Report not found');const fight=(report.fights||[]).find(f=>+f.id===+fightId)||report.fights?.[0];if(!fight)throw new Error('Fight not found');const friendly=new Set(fight.friendlyPlayers||[]),positions=[],events=[];for(const e of rawEvents){const ts=(Number(e.timestamp)||0)-Number(fight.startTime||0);if(ts<0)continue;const sr=readResource(e.sourceResources||e.resources||e.source?.resources);if(sr&&e.sourceID&&friendly.has(e.sourceID))positions.push({actorId:e.sourceID,t:ts,x:sr.x,y:sr.y});const tr=readResource(e.targetResources||e.target?.resources);if(tr&&e.targetID&&friendly.has(e.targetID))positions.push({actorId:e.targetID,t:ts,x:tr.x,y:tr.y});if(Number.isFinite(+e.x)&&Number.isFinite(+e.y)&&e.sourceID&&friendly.has(e.sourceID))positions.push({actorId:e.sourceID,t:ts,x:+e.x,y:+e.y});if(e.type==='cast'||e.type==='begincast'||e.type==='death'||e.type==='applydebuff'||e.type==='removebuff'||e.type==='summon'){events.push({t:ts,type:e.type,label:e.ability?.name||e.abilityName||e.type,abilityID:e.abilityGameID||e.ability?.guid||null,sourceID:e.sourceID,targetID:e.targetID})}}
 positions.sort((a,b)=>a.t-b.t);const compact=[];const last=new Map();for(const p of positions){const prev=last.get(p.actorId);if(!prev||p.t-prev.t>=250||Math.abs(p.x-prev.x)+Math.abs(p.y-prev.y)>20){compact.push(p);last.set(p.actorId,p)}}return {source:'warcraftlogs',report:{code:reportCode,title:report.title},fight:{id:fight.id,name:fight.name,startTime:fight.startTime,endTime:fight.endTime,duration:fight.endTime-fight.startTime,encounterID:fight.encounterID,difficulty:fight.difficulty,kill:fight.kill},actors:(report.masterData?.actors||[]).filter(a=>friendly.has(a.id)),positions:compact,events,duration:fight.endTime-fight.startTime}}
export default {async fetch(request,env){const u=new URL(request.url);if(request.method==='OPTIONS')return new Response('',{headers:cors(env.ALLOWED_ORIGIN||'*')});if(u.pathname==='/health')return new Response(JSON.stringify({ok:true}),{headers:cors(env.ALLOWED_ORIGIN||'*')});if(u.pathname!=='/replay')return new Response(JSON.stringify({error:'Use /replay?report=CODE&fight=ID'}),{status:404,headers:cors(env.ALLOWED_ORIGIN||'*')});try{const report=u.searchParams.get('report'),fight=+u.searchParams.get('fight');if(!report||!fight)throw new Error('report and fight are required');const meta=await gql(env,META,{code:report,fightIDs:[fight]});let start=null,all=[],guard=0;while(guard++<30){const page=await gql(env,EVENTS,{code:report,fightIDs:[fight],startTime:start});const ev=page.reportData?.report?.events;if(!ev)break;all.push(...(ev.data||[]));if(!ev.nextPageTimestamp||ev.nextPageTimestamp===start)break;start=ev.nextPageTimestamp}const result=normalize(meta,all,report,fight);return new Response(JSON.stringify(result),{headers:cors(env.ALLOWED_ORIGIN||'*')})}catch(e){return new Response(JSON.stringify({error:String(e.message||e)}),{status:500,headers:cors(env.ALLOWED_ORIGIN||'*')})}}};
